name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        username: ajAcr1
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ajacr1.azurecr.io
    
    - name: Build the Docker image
      run: |
        docker build . --tag ajacr1.azurecr.io/my-go-sample
        docker push ajacr1.azurecr.io/my-go-sample
        docker rmi ajacr1.azurecr.io/my-go-sample
    
    - uses: shigupt202/local-container-scan@releases/v1
      name: Scanning image
      with:
        image-name: ajacr1.azurecr.io/my-go-sample
        
