name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        username: ajAcr1
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ajacr1.azurecr.io
    
    - name: Build the Docker image
      run: |
        docker build . --tag ajacr1.azurecr.io/my-go-sample
    
    - uses: ds-ms/container-scan@releases/v0
      name: imagescan
      id: imagescan
      continue-on-error: true
      with:
        image-name: ajacr1.azurecr.io/my-go-sample
        username: ajAcr1
        password: ${{ secrets.DOCKER_PASSWORD }}
        run-quality-checks: false
    
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: container-scan-report
        path: ${{ steps.imagescan.outputs.sarif-file-path }}
