name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag my-go-sample
    
    - uses: shigupt202/local-container-scan@releases/v1
      name: Scanning image
      with:
        image-name: my-go-sample
